### PR TITLE
Migrated from Zend to Laminas

### PR DESCRIPTION
**Pull request by lucaguindani**

### CODE REVIEW

**Comment by PowerKiKi** [comment]
You probably want to search and replace "`Zend\`" as the migration tool miss a few one (as seen in https://scrutinizer-ci.com/g/unil-lettres/dilps-tiresias/inspections/c0dabdd7-9d50-44a8-9751-302e2aaf7645/issues/files/tests/data/query/student-can-create-card.php?status=failed&conditionIds%5B0%5D=426415)

**Comment by lucaguindani** [comment]
Yes I've done that with the latest commit (c4e3d36), but their is still some getInstance() issues.

https://scrutinizer-ci.com/g/unil-lettres/dilps-tiresias/inspections/3072452d-27d1-43e3-8aed-22cc3132c903

Do you think it's something that can be easily fixed ?

**Comment by PowerKiKi** [comment]
Thanks to [PHP 7.4 contravariance](https://www.php.net/manual/en/migration74.new-features.php#migration74.new-features.core.type-variance) you should be able to properly type hint:

```diff
-    public function assert(Acl $acl, RoleInterface $role = null, ResourceInterface $resource = null, $privilege = null)
+    public function assert(Acl $acl, RoleInterface $role = null, ModelResource $resource = null, $privilege = null)
```

**Comment by PowerKiKi** [comment]
But then PHP 7.4 becomes a requirement, not just a compatibility, and you should [update your composer.json](https://github.com/unil-lettres/dilps-tiresias/blob/develop/composer.json#L29) as such.

**Comment by lucaguindani** [comment]
I'm not planning to update the server to 7.4 just yet, so I'll have to leave the composer php requirement as it is for now.

**Comment by lucaguindani** [comment]
Is there another way to remove those issues without having to require 7.4 ?

**Comment by PowerKiKi** [comment]
You might try to change phpdoc. That should work. Otherwise ignore them until PHP 7.4 (they always existed)

**Pull request merged**
